### ISSUE TITLE
Broken with new expl3

### ISSUE THREAD

**Issue by pthariensflame** [mhelvens/latex-withargs#2]
(This is as of October 21, 2016.)

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
/usr/local/texlive/2016/texmf-dist/tex/latex/withargs/withargs.sty:155: LaTeX e
rror: "kernel/non-base-function"
! 
! Function '\__withargs_var:nx' is not a base function
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
```

**Comment by mhelvens** [comment]
I see. So they changed some core stuff in expl3, I see. I'll try to look into this, but it will probably have to wait a few weeks. I'm pretty busy at work.

I haven't used LaTeX at all for a year or two, so neither my computer nor my mind are really in LaTeX mode right now. I imagine fixing this problem is probably easy, though. If someone else could create a pull request, that would be awesome.
